
trainer:
  name: "FixmatchCCSSL_Trainer"
  epochs: 600
  eval_steps: 200
  save_epoch: 1
  ema:
    use: true
    decay: 0.999
    pseudo_with_ema: false

  optimizer:
    name: 'Momentum'
    learning_rate: 0.03    # 0.03
    momentum: 0.9
    weight_decay: 0.001
    use_nesterov: true
    scheduler:
      name: 'cosine_schedule_with_warmup'
      num_warmup_steps: 0
      num_training_steps: 524800



dataset:
  name: "CIFAR10SSL"
  mean: &sign_mean [0.4914, 0.4822, 0.4465]
  std: &sign_std [0.2471, 0.2435, 0.2616]
  num_classes: &sign_num_classes 10
  num_labeled: 250
  batch_size: 64
  mu: 7
  num_workers: 4
  data:
    root: "./data/CIFAR/"
    train_transform:
      labeld_transform:
        -
          - RandomHorizontalFlip:
              prob: 0.5
          - RandomCrop:
              size: 32
              padding: 4
              padding_mode: "reflect"
          - ToTensor:
          - Normalize:
              mean: *sign_mean
              std: *sign_std
      unlabeld_transform:
        -
          - RandomHorizontalFlip:
              prob: 0.5
          - RandomCrop:
              size: 32
              padding: 4
              padding_mode: 'reflect'
          - ToTensor:
          - Normalize:
              mean: *sign_mean
              std: *sign_std
        -
          - RandomHorizontalFlip:
              prob: 0.5
          - RandomCrop:
              size: 32
              padding: 4
              padding_mode: 'reflect'
          - RandAugmentMC:
              n: 2
              m: 10
          - ToTensor:
          - Normalize:
              mean: *sign_mean
              std: *sign_std
        -
          - RandomResizedCrop:
              size: 32
          - RandomHorizontalFlip:
              prob: 0.5
          - RandomApply:
              transforms:
                - ColorJitter:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1
              p: 0.8
          - RandomGrayscale:
              p: 0.2
          - ToTensor:
          # - Normalize:
          #     mean: *sign_mean
          #     std: *sign_std

    val_transform:
      -
        - ToTensor:
        - Normalize:
          mean: *sign_mean
          std: *sign_std
        

model:
  name: "wideresnet"
  widen_factor: 2
  depth: 28
  drop_rate: 0
  num_classes: *sign_num_classes
  low_dim: 64
  proj: True
  proj_after: false



loss:
  name: "ccssl_loss"
  lambda_u: 1
  lambda_c: 1
  threshold: 0.95
  T: 1
  loss_x:
    name: "CrossEntropyLoss"
    reduction: "mean"
  loss_u:
    name: "CrossEntropyLoss"
    reduction: "none"
  loss_c:
    name: "SoftSupConLoss"
    temperature: 0.07


metric:
  - top1_acc
  - top1_pseudo_acc

